# Generated by Django 5.0 on 2023-12-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "car_brand",
                    models.CharField(max_length=50, verbose_name="Car brand"),
                ),
                (
                    "car_model",
                    models.CharField(max_length=50, verbose_name="Car model"),
                ),
                ("car_year", models.CharField(max_length=4, verbose_name="Car year")),
                (
                    "status",
                    models.CharField(
                        choices=[("RDY", "Ready"), ("BSY", "Busy")],
                        default="RDY",
                        max_length=5,
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carsharing.car"
                    ),
                ),
                (
                    "renter_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
