# Generated by Django 5.0 on 2023-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carsharing", "0003_remove_car_id_remove_car_renter_car_car_id_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="id",
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
