[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["Jqsm6 <jqsm6@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
